apiVersion: v1
kind: ResourceQuota
metadata:
  name: itashi
spec:
  hard:
    cpu: 2000m
    memory: 4Gi
    pods: 20
---
apiVersion: v1
kind: LimitRange
metadata:
  name: itashi
spec:
  limits:
  - defaultRequest:
      cpu: 25m
      memory: 50Mi
    default:
      cpu: 50m
      memory: 100Mi
    min:
      cpu: 25m
      memory: 50Mi
    max:
      cpu: 150m
      memory: 300Mi
    type: Container
---
apiVersion: v1
kind: Pod
metadata:
  name: httpd
  labels:
    name: httpd
spec:
  containers:
  - name: httpd
    image: itashi/httpd:1.2
    resources:
      limits:
        memory: "128Mi"
        cpu: "150m"
    ports:
      - containerPort: 80
        name: httpd
        
---
